### ISSUE TITLE
TypeError: 'numpy.float64' object cannot be interpreted as an integer

### ISSUE THREAD

**Issue by StephenLee2016** [masabdi/LSPS#9]
Hi, 
When i run python depth_train.py --config ../exps/nnyu.yaml --mode pretrain , met below error, any advice? 

Thanks

```
self.image_save_iterations=2500
self.snapshot_prefix='../outputs/nnyu/pre'
self.display=10
create data
(300, 300, 300)
Loading cache data from /posenet/LSPS/datasets/cache//NYUImporter_train_synth_None_True_32_gt_300__cache.pkl
Shuffling
 data loaded with 36378 samples
create data
Loading cache data from /posenet/LSPS/datasets/cache//NYUImporter_train_None_True_32_gt_300__cache.pkl
Shuffling
 data loaded with 36378 samples
create data
Loading cache data from /posenet/LSPS/datasets/cache//NYUImporter_test_None_True_32_gt_300__cache.pkl
 data loaded with 4126 samples
using 1.00 percent of the labeled real data
Failed to load the parameters of vae
Traceback (most recent call last):
  File "depth_train.py", line 272, in <module>
    main(sys.argv)
  File "depth_train.py", line 146, in main
    enumerate(izip(train_loader_a,train_loader_b)):
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 313, in __next__
    indices = next(self.sample_iter)  # may raise StopIteration
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/sampler.py", line 138, in __iter__
    for idx in self.sampler:
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/sampler.py", line 51, in __iter__
    return iter(torch.randperm(len(self.data_source)).tolist())
TypeError: 'numpy.float64' object cannot be interpreted as an integer
```

**Comment by StephenLee2016** [comment]
I solved this error by change py3 to py2
